---

roles:
  - name: geerlingguy.mysql
  # monitoring
  - name: cloudalchemy.node-exporter
  - name: cloudalchemy.prometheus
  - name: rockylinux.ipsilon
    src: https://github.com/rocky-linux/ansible-role-ipsilon
    version: main

collections:
  # freeipa
  - name: freeipa.ansible_freeipa
    version: 0.3.1
  - name: community.general
  - name: community.mysql
  - name: ansible.posix
