---

roles:
  - name: geerlingguy.mysql
  # monitoring
  - name: cloudalchemy.node_exporter
  - name: cloudalchemy.prometheus
  - name: cloudalchemy.alertmanager
  - name: cloudalchemy.grafana
  - name: geerlingguy.gitlab
  - name: geerlingguy.postgresql
  - name: geerlingguy.php
  - name: geerlingguy.nodejs
  - name: riemers.gitlab-runner


  - name: rockylinux.ipagetcert
    src: https://github.com/rocky-linux/ansible-role-ipa-getcert
    version: main
  - name: rockylinux.ipsilon
    src: https://github.com/rocky-linux/ansible-role-ipsilon
    version: main
  - name: rockylinux.kojihub
    src: https://github.com/rocky-linux/ansible-role-kojihub
    version: main
  - name: rockylinux.kojid
    src: https://github.com/rocky-linux/ansible-role-kojid
    version: main
  - name: rockylinux.rabbitmq
    src: https://github.com/rocky-linux/ansible-role-rabbitmq
    version: main
  - name: rockylinux.sigul
    src: https://github.com/rocky-linux/ansible-role-sigul
    version: main
  - name: rockylinux.matterbridge
    src: https://github.com/NeilHanlon/ansible-role-matterbridge
    version: master
  - name: rockylinux.pinnwand
    src: https://github.com/rocky-linux/ansible-role-pinnwand
    version: main
  - name: rockylinux.wikijs
    src: https://git.rockylinux.org/infrastructure/public/ansible/ansible-role-wikijs.git
    scm: git
    version: develop

collections:
  # freeipa
  - name: freeipa.ansible_freeipa
    version: 0.3.6
  - name: community.general
  - name: community.mysql
  - name: community.rabbitmq
  - name: ansible.posix
  - name: ktdreyer.koji_ansible
  - name: netbox.netbox
  - name: community.aws
  - name: containers.podman
  - name: nginxinc.nginx_core
    version: 0.3.0
# - name: rockylinux.taiga
#   source: https://github.com/rocky-linux/taiga-ansible.git
#   type: git
#   version: master
