---
ipagroups:
  - group: infrastructure
    description: Infrastructure Team
  - group: operations
    description: Operations Team
  - group: development
    description: Development Team
  - group: qa
    description: Quality Assurance Team
  - group: marketing
    description: Marketing
  - group: rockyadm
    description: Rocky Linux Administrators - Only Admin Accounts
