---
# https://github.com/ansible/ansible-lint-action
name: Ansible Lint

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Add installed collections in Ansible configuration
        run: |
          echo '[defaults]' > ansible.cfg
          echo 'collections_paths = ./collections' >> ansible.cfg

      - name: Install role requirements
        run: ansible-galaxy role install -r ansible/roles/requirements.yml

      - name: Install collection requirements
        run: ansible-galaxy collection install -r ansible/roles/requirements.yml

      - name: Ansible Lint
        uses: rocky-linux/ansible-lint-action@master
        with:
          args: "--exclude .github"
